pipeline {
    agent {
        label 'AGENT-1'
    
    }
    parameters {
        
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        
    }
    options{
        timeout( time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('INIT and PLAN') { 
            steps {
                withAWS(credentials: 'aws-cred', region: 'us-east-1') {
              sh  """
                 cd 00-vpc
                 terraform init -reconfigure
                 terraform plan -out=tfplan
                 
                  """
              
            }
        }
        }
        stage('Test') { 
            steps {
               sh   'echo this is test'
               sh 'echo test again'
            }
        }
        stage('Deploy') { 
            when{
                expression { env.GIT_BRANCH == 'origin/main'}
            }
            steps {
                sh 'echo this is deploy'
                
            }
        }
        stage('print params') { 
            steps {
                echo " Hello ${params.PERSON}"
                echo " biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
                
            }
        }
         
         
        stage('Approval') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
    
    }
        post { 
        always { 
            deleteDir()
        }
        success{
             
             echo 'this section runs when pipeline success'
         }
        failure{
             echo 'this section runs when pipeline failure'
        }
    }

}