pipeline {
    agent {
        label 'AGENT-1'
    
    }
    parameters {
        
        choice(name: 'CHOICE', choices: ['apply', 'destroy'], description: 'Pick something')

        
    }
    options{
        timeout( time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('INIT and PLAN') { 
            steps {
                withAWS(credentials: 'aws-cred', region: 'us-east-1') {
              sh  """
                 cd 00-vpc
                 terraform init -reconfigure
                 terraform plan -out=tfplan
                 
                  """
              
            }
        }
        }
        
         
         
        
    
    }
        post { 
        always { 
            deleteDir()
        }
        success{
             
             echo 'this section runs when pipeline success'
         }
        failure{
             echo 'this section runs when pipeline failure'
        }
    }

}