pipeline {
    agent {
        label 'AGENT-1'
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('INIT and PLAN') {
            steps {
                withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        stage('Apply or Destroy') {
            steps {
                withAWS(credentials: 'aws-cred', region: 'us-east-1') {
                    sh """
                        cd 10-sg
                        if [ "${params.ACTION}" = "apply" ]; then
                            terraform apply -auto-approve tfplan
                        elif [ "${params.ACTION}" = "destroy" ]; then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }

         
        
        }

    post {
        always {
            deleteDir()
        }
        success {
            echo 'this section runs when pipeline success'
        }
        failure {
            echo 'this section runs when pipeline failure'
        }
    }
}
